variables:
  GIT_STRATEGY: clone
stages:
  - image

build_ps_image:
    stage: image
    tags:
      - tupack
    before_script:
      - export VERSION=$(cat VERSION)
      - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin ${CI_REGISTRY}
    script:
      - docker build -t $CI_REGISTRY_IMAGE:$VERSION .
      # push to project gitlab registry
      - docker push $CI_REGISTRY_IMAGE:$VERSION
      # delete from local registry
      - docker rmi $CI_REGISTRY_IMAGE:$VERSION
    only:
      - master