apiVersion: apps/v1
kind: Deployment
metadata:
    name: gitlab-search-ui
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gitlab-search-ui
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: gitlab-search-ui
        spec:
            containers:
            -   name: gitlab-search-ui
                image: registry.gitlab.com/tufinps/tos2/ps_utils/gitlab_search_ui:0.1.4
                ports:
                -   containerPort: 80
                env:
                    - name: TOKEN
                      valueFrom:
                          secretKeyRef:
                              name: build-tos2-package-secret
                              key: token
                    - name: GROUP
                      value: "8708408"
                    - name: REQUESTS_PER_PAGE
                      value: "100"
            imagePullSecrets:
            - name: registry-credentials

