apiVersion: apps/v1
kind: Deployment
metadata:
    name: gitlab_search_ui
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gitlab_search_ui
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: gitlab_search_ui
        spec:
            containers:
            -   name: gitlab_search_ui
                image: registry.gitlab.com/tufinps/tos2/gitlab_search_ui
                ports:
                -   containerPort: 80
                env:
                    - name: TOKEN
                      valueFrom:
                          secretKeyRef:
                              name: gitlab_search_ui-secret
                              key: TOKEN
                    - name: GROUP
                      value: "8708408"
                    - name: REQUESTS_PER_PAGE
                      value: 100
            imagePullSecrets:
            - name: registry-credentials

